import Head from 'next/head'
import Image from "next/image"
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home = ({photos}) =>{
  return(
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      
        <div className={styles.grid}>
          <Link href="/list">
            <a>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
            </a>
          </Link>
        </div>

        <ul>
        {photos.map((post) => (
          <li key={post.id}>
            {/* リンク先を指定 */}
            <Link href={`/details/${post.id}`}>
              <a>{post.title}</a>
            </Link>
          </li>
        ))}
        </ul>


        <img src="/next_hisa/vercel.svg" />
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts")
  const photos = await res.json()  
  return {
    props: {
      photos,
    },
  }
}

export default Home